baseURL = 'https://its-ashu-otf.github.io/'

title = "Ashu's 0Day Arsenal"

theme = "dream"

languageCode = "en-us"

[params]
#zenMode = true
 
lightTheme = "light"
darkTheme = "dark"
 
# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""
 
images = ["me/background.jpg"]
 
author = "Ashutosh Gupta"
description = "Ashu's Personal Blog"
avatar = "me/ashu.jpg"
headerTitle = "Ashu's 0Day Arsenal"
motto = "The Arsenal for Ethical Hackers and Cyber Defenders"
 
footerBottomText = "Website Made by @its-ashu-otf :: All Right's Reserved ©"
 
rss = false
 
utterancesRepo = "its-ashu-otf/its-ashu-otf.github.io"
 
# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
 
# waline = true
# walineServer = ""
 
email = "its-ashu-otf@gmail.com"
 
siteStartYear = 2025
 
favicon = "favicon.png"
 
# Syntax highlighting
customSyntaxHighlighting = true

[markup]
[markup.highlight]
noClasses = false
 
# options
stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]
 
[params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []
 
[params.experimental]
jsDate = true
jsDateFormat = "yyyy-MM-dd"

enableRobotsTXT = true
