name: Deploy Hugo site to GitHub Pages

on:
  # Trigger the workflow when pushing to the main branch
  push:
    branches:
      - main

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

permissions:
  contents: write  # Allow pushing to the main branch

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.4
    steps:
      # Install Hugo CLI
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      # Install Node.js dependencies (if applicable)
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"

      # Build the Hugo site
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: |
          hugo \
            --gc \
            --minify

      # Deploy to the main branch
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GHPAGES }}
        run: |
          # Set up Git config
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure public directory exists
          if [ ! -d "public" ]; then
            echo "Error: 'public' directory not found. Check your Hugo build step."
            exit 1
          fi

          # Clean up existing files and copy new files
          rm -rf *
          cp -r public/* .
          git add .
          git commit -m "Deploy site to GitHub Pages"
          git push --force --set-upstream origin main
